site_name: js-sequence-diagram with MkDocs example

extra_javascript:
    - js/umlconvert.js 
    - https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js
    - https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js
    - https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js
    - https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js

markdown_extensions:
    - pymdownx.superfences:
        custom_fences: [
          {name: sequence, class: uml-sequence-diagram}
        ]
